apiVersion: v1
kind: Service
metadata:
  name: ${PROJECT_NAME} #<service.name>
  labels:
    app: ${PROJECT_NAME} #<service.name>
  namespace: farming #<service.namespace>

spec:
  type: LoadBalancer
  selector:
    app: ${PROJECT_NAME} #<service.name>
---
apiVersion: v1
kind: Service
metadata:
  name: ${PROJECT_NAME}-headless #<service.name>
  labels:
    app: ${PROJECT_NAME} #<service.name>
  namespace: farming #<service.namespace>

spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: ${PROJECT_NAME} #<service.name>
