// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// IdentifyServiceClient is the client API for IdentifyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IdentifyServiceClient interface {
	Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*RegisterRsp, error)
}

type identifyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIdentifyServiceClient(cc grpc.ClientConnInterface) IdentifyServiceClient {
	return &identifyServiceClient{cc}
}

func (c *identifyServiceClient) Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*RegisterRsp, error) {
	out := new(RegisterRsp)
	err := c.cc.Invoke(ctx, "/service.IdentifyService/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IdentifyServiceServer is the server API for IdentifyService service.
// All implementations must embed UnimplementedIdentifyServiceServer
// for forward compatibility
type IdentifyServiceServer interface {
	Register(context.Context, *RegisterReq) (*RegisterRsp, error)
	mustEmbedUnimplementedIdentifyServiceServer()
}

// UnimplementedIdentifyServiceServer must be embedded to have forward compatible implementations.
type UnimplementedIdentifyServiceServer struct {
}

func (UnimplementedIdentifyServiceServer) Register(context.Context, *RegisterReq) (*RegisterRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedIdentifyServiceServer) mustEmbedUnimplementedIdentifyServiceServer() {}

// UnsafeIdentifyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IdentifyServiceServer will
// result in compilation errors.
type UnsafeIdentifyServiceServer interface {
	mustEmbedUnimplementedIdentifyServiceServer()
}

func RegisterIdentifyServiceServer(s grpc.ServiceRegistrar, srv IdentifyServiceServer) {
	s.RegisterService(&IdentifyService_ServiceDesc, srv)
}

func _IdentifyService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentifyServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.IdentifyService/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentifyServiceServer).Register(ctx, req.(*RegisterReq))
	}
	return interceptor(ctx, in, info, handler)
}

// IdentifyService_ServiceDesc is the grpc.ServiceDesc for IdentifyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IdentifyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "service.IdentifyService",
	HandlerType: (*IdentifyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _IdentifyService_Register_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "identity.proto",
}
