apiVersion: apps/v1
kind: Deployment
metadata:
  name: not-important
spec:
  template:
    spec:
      containers:
        - name: ${PROJECT_NAME} #<service.name>

          ports:
            - name: grpc-port
              containerPort: 28086 #<api.grpc.port>
            - name: http-port
              containerPort: 28088 #<api.restful.port>
