apiVersion: v1
kind: Service
metadata:
  name: negligible

spec:
  ports:
    - name: grpc-port
      port: 28086 #<api.grpc.port>
      protocol: TCP
      targetPort: 28086 #<api.grpc.port>
    - name: http-port
      port: 28088 #<api.restful.port>
      protocol: TCP
      targetPort: 28088 #<api.restful.port>
