// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package server

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GroundServiceClient is the client API for GroundService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GroundServiceClient interface {
	SelectGround(ctx context.Context, in *GroundReq, opts ...grpc.CallOption) (*GroundRsp, error)
}

type groundServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGroundServiceClient(cc grpc.ClientConnInterface) GroundServiceClient {
	return &groundServiceClient{cc}
}

func (c *groundServiceClient) SelectGround(ctx context.Context, in *GroundReq, opts ...grpc.CallOption) (*GroundRsp, error) {
	out := new(GroundRsp)
	err := c.cc.Invoke(ctx, "/server.GroundService/SelectGround", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GroundServiceServer is the server API for GroundService service.
// All implementations must embed UnimplementedGroundServiceServer
// for forward compatibility
type GroundServiceServer interface {
	SelectGround(context.Context, *GroundReq) (*GroundRsp, error)
	mustEmbedUnimplementedGroundServiceServer()
}

// UnimplementedGroundServiceServer must be embedded to have forward compatible implementations.
type UnimplementedGroundServiceServer struct {
}

func (UnimplementedGroundServiceServer) SelectGround(context.Context, *GroundReq) (*GroundRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SelectGround not implemented")
}
func (UnimplementedGroundServiceServer) mustEmbedUnimplementedGroundServiceServer() {}

// UnsafeGroundServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GroundServiceServer will
// result in compilation errors.
type UnsafeGroundServiceServer interface {
	mustEmbedUnimplementedGroundServiceServer()
}

func RegisterGroundServiceServer(s grpc.ServiceRegistrar, srv GroundServiceServer) {
	s.RegisterService(&GroundService_ServiceDesc, srv)
}

func _GroundService_SelectGround_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GroundReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroundServiceServer).SelectGround(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/server.GroundService/SelectGround",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroundServiceServer).SelectGround(ctx, req.(*GroundReq))
	}
	return interceptor(ctx, in, info, handler)
}

// GroundService_ServiceDesc is the grpc.ServiceDesc for GroundService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GroundService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "server.GroundService",
	HandlerType: (*GroundServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SelectGround",
			Handler:    _GroundService_SelectGround_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ground.proto",
}
