// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.6.1
// source: ground.proto

package server

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GroundReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Kind  string `protobuf:"bytes,1,opt,name=Kind,proto3" json:"Kind,omitempty"`
	Owner string `protobuf:"bytes,2,opt,name=Owner,proto3" json:"Owner,omitempty"`
}

func (x *GroundReq) Reset() {
	*x = GroundReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ground_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GroundReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroundReq) ProtoMessage() {}

func (x *GroundReq) ProtoReflect() protoreflect.Message {
	mi := &file_ground_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroundReq.ProtoReflect.Descriptor instead.
func (*GroundReq) Descriptor() ([]byte, []int) {
	return file_ground_proto_rawDescGZIP(), []int{0}
}

func (x *GroundReq) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *GroundReq) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

type GroundRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GroundId string `protobuf:"bytes,1,opt,name=GroundId,proto3" json:"GroundId,omitempty"`
	Position string `protobuf:"bytes,2,opt,name=Position,proto3" json:"Position,omitempty"`
	Owner    string `protobuf:"bytes,3,opt,name=Owner,proto3" json:"Owner,omitempty"`
	Price    int64  `protobuf:"varint,4,opt,name=Price,proto3" json:"Price,omitempty"`
}

func (x *GroundRsp) Reset() {
	*x = GroundRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ground_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GroundRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroundRsp) ProtoMessage() {}

func (x *GroundRsp) ProtoReflect() protoreflect.Message {
	mi := &file_ground_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroundRsp.ProtoReflect.Descriptor instead.
func (*GroundRsp) Descriptor() ([]byte, []int) {
	return file_ground_proto_rawDescGZIP(), []int{1}
}

func (x *GroundRsp) GetGroundId() string {
	if x != nil {
		return x.GroundId
	}
	return ""
}

func (x *GroundRsp) GetPosition() string {
	if x != nil {
		return x.Position
	}
	return ""
}

func (x *GroundRsp) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *GroundRsp) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

var File_ground_proto protoreflect.FileDescriptor

var file_ground_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x67, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61,
	0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x35, 0x0a, 0x09, 0x47, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x52, 0x65,
	0x71, 0x12, 0x12, 0x0a, 0x04, 0x4b, 0x69, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x4b, 0x69, 0x6e, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x22, 0x6f, 0x0a, 0x09, 0x47,
	0x72, 0x6f, 0x75, 0x6e, 0x64, 0x52, 0x73, 0x70, 0x12, 0x1a, 0x0a, 0x08, 0x47, 0x72, 0x6f, 0x75,
	0x6e, 0x64, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x47, 0x72, 0x6f, 0x75,
	0x6e, 0x64, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x14, 0x0a, 0x05, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x50, 0x72, 0x69, 0x63, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x50, 0x72, 0x69, 0x63, 0x65, 0x32, 0x6d, 0x0a, 0x0d,
	0x47, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x5c, 0x0a,
	0x0c, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x47, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x12, 0x11, 0x2e,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x47, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x52, 0x65, 0x71,
	0x1a, 0x11, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x47, 0x72, 0x6f, 0x75, 0x6e, 0x64,
	0x52, 0x73, 0x70, 0x22, 0x26, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x20, 0x22, 0x1b, 0x2f, 0x47, 0x72,
	0x6f, 0x75, 0x6e, 0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x53, 0x65, 0x6c, 0x65,
	0x63, 0x74, 0x47, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x3a, 0x01, 0x2a, 0x42, 0x0e, 0x5a, 0x0c, 0x2e,
	0x2f, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_ground_proto_rawDescOnce sync.Once
	file_ground_proto_rawDescData = file_ground_proto_rawDesc
)

func file_ground_proto_rawDescGZIP() []byte {
	file_ground_proto_rawDescOnce.Do(func() {
		file_ground_proto_rawDescData = protoimpl.X.CompressGZIP(file_ground_proto_rawDescData)
	})
	return file_ground_proto_rawDescData
}

var file_ground_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_ground_proto_goTypes = []interface{}{
	(*GroundReq)(nil), // 0: server.GroundReq
	(*GroundRsp)(nil), // 1: server.GroundRsp
}
var file_ground_proto_depIdxs = []int32{
	0, // 0: server.GroundService.SelectGround:input_type -> server.GroundReq
	1, // 1: server.GroundService.SelectGround:output_type -> server.GroundRsp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ground_proto_init() }
func file_ground_proto_init() {
	if File_ground_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ground_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GroundReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ground_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GroundRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ground_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ground_proto_goTypes,
		DependencyIndexes: file_ground_proto_depIdxs,
		MessageInfos:      file_ground_proto_msgTypes,
	}.Build()
	File_ground_proto = out.File
	file_ground_proto_rawDesc = nil
	file_ground_proto_goTypes = nil
	file_ground_proto_depIdxs = nil
}
